services:
  api:
    image: api-prod
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: prod
    ports:
      - "3000:3000"       # Adjust port if needed
    environment:
      NODE_ENV: production
  analytics:
    image: analytics-prod
    build:
      context: .
      dockerfile: apps/analytics/Dockerfile
      target: prod
    environment:
      NODE_ENV: production
  pool-manager:
    image: pool-manager-prod
    build:
      context: .
      dockerfile: apps/pool-manager/Dockerfile
      target: prod
    environment:
      NODE_ENV: production