services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "3000:3000"       # Adjust port if needed
    environment:
      NODE_ENV: production
  analytics:
    build:
      context: .
      dockerfile: apps/analytics/Dockerfile
    ports:
      - "3001:3000"       # Adjust port if needed
    environment:
      NODE_ENV: production
  pool-manager:
    build:
      context: .
      dockerfile: apps/pool-manager/Dockerfile
    ports:
      - "3002:3000"       # Adjust port if needed
    environment:
      NODE_ENV: production